const competitions = [
  {
    id: 1,
    name: "Carrera de Primavera",
    date: "2024-05-15", 
    time: "10:00 AM",
    location: "Río Miño",
    categories: ["Alevín", "Cadete", "Juvenil"],
    genders: ["Masculino", "Femenino"],
    league: "Liga Gallega de Batel",
    level: "Campeonato Gallego",
  },
  {
    id: 2,
    name: "Campeonato Regional",
    date: "2024-06-10", 
    time: "11:00 AM",
    location: "Lago de Castrelo",
    categories: ["Juvenil", "Absoluto"],
    genders: ["Masculino", "Femenino"],
    league: "Liga Gallega de Trainerillas",
    level: "Provincial",
  },
  {
    id: 3,
    name: "Maratón del Río Miño",
    date: "2024-07-25", 
    time: "09:00 AM",
    location: "Praia de Chapela",
    categories: ["Absoluto", "Veterano"],
    genders: ["Masculino", "Femenino"],
    league: "Liga Gallega de Traineras",
    level: "Campeonato de España",
  },
  {
    id: 4,
    name: "Regata La Guía Vigo",
    date: "2024-07-29", 
    time: "10:00 AM",
    location: "ETEA",
    categories: ["Absoluto"],
    genders: ["Masculino", "Femenino"],
    league: "Liga Gallega de Batel",
    level: "Provincial",
  },
];

export default competitions;
